### ISSUE TITLE
Start daemon automatically after install

### ISSUE THREAD

**Issue by pelcasandra** [yorokobicom/agent#1]
Start yorokobi daemon automatically after installation so users don't need to.

**Comment by Sonkun** [comment]
This should be covered by the system service.

Basically, a file `/etc/systemd/system/yorokobi.service` that looks like this.

```
[Unit]
Description=Yorokobi Agent

[Service]
Type=simple
ExecStart=/usr/bin/yorokobid --conf /etc/yorokobi.conf --pid /var/log/yorokobi.log

[Install]
WantedBy=multi-user.target
```

After a `systemctl daemon-reload`, the Yorokobi agent becomes available a system service which you can start, stop and mark as "start as boot time".

```
sudo systemctl start|stop yorokobi # start and stop the agent
sudo systemctl enable yorkobi # start it at boot time
```

It's the Debian package role to install that file and request the service to start at boot time.

**Comment by Sonkun** [comment]
With snap package (https://snapdocs.labix.org/service-management/3965), you do:

```
sudo snap start|stop|restart yorokobi.daemon
```
