### ISSUE TITLE
Check for backup.state before sending backup

### ISSUE THREAD

**Issue by pelcasandra** [yorokobicom/agent#19]
I just implemented a new `waiting` state in backups when remofile is effectively started. This state means that is ready and waiting to receive the backup.

**Important**: This requires `remofile start` command to return finished (see email I sent you regarding this) otherwise It won't work as it will keep waiting for this signal to change the state. 

You can do a `GET` request to this endpoint including the backup `id`:

    GET https://api.yorokobi.com/v1/backups/:id 

It will return a JSON like this

```
{
    "id": "ucQBK48NGZpurvM6b5Vy",
    "hostname": "127.0.0.1",
    "port": 85571,
    "token": "ucQBK48NGZpurvM6b5Vy",
    "state": "waiting"
}
```

You should perform a request to the backup before sending and if its state is not `waiting` you should try again after n seconds and abort after some attempts.

**Comment by Sonkun** [comment]
OKi, will start implementing this in one hour.

**Comment by Sonkun** [comment]
OK done, but the server never seems to answer "waiting".

As I was saying, Remofile is handling the delayed Remofile server instance startup removing the need for such synchronization mechanism. If you want to try it yourself, upload a  file and start the server few seconds later. Uploading the file will start as soon as the server is up.

```
export REMOFILE_HOSTNAME=localhost
export REMOFILE_PORT=12346
export REMOFILE_TOKEN=abcdefgh

# from terminal 1
remofile upload my-backup.zip / --progress

# from terminal 2
remofile run root-dir/ 12346 abcdefgh
```

As long as the server is up within the timeout value set on the client side, it's no problem.

**Comment by pelcasandra** [comment]
Oh, I didn't know this! If this is the case, then there is no need to use waiting state? If so, remove this waiting check you just implemented.
