### ISSUE TITLE
Remove password request after enter license

### ISSUE THREAD

**Issue by pelcasandra** [yorokobicom/agent#2]
Authentication is performed entering only the license. 

Remove asking for Yorokobi account password here which is not needed and causes confusion to users.

```
Enter your license Key below.
License key: xxxxxx
Now enter your account password.
Password: 
Please wait, attempting to authenticate your license...
Success. Your license key worked fine :-)
```

**Comment by Sonkun** [comment]
How do you make the HTTP request without the password ?

**Comment by pelcasandra** [comment]
It is not needed. The license acts as authentication token.

**Comment by Sonkun** [comment]
OK, let's have a look at a curl command, can you fix the following so I understand how it works.

```
curl --user <license_key>:<account_password> \
  --header "Content-Type: application/json" \
  --request POST \
  --data '{"hostname":"<hostname>","ip_address":"<ip_address>"}' \
  https://api.yorokobi.com/v1/agents
```
